trigger:
- '*'

pr:
  branches:
    include:
    - '*'
  autoCancel: false

variables:
  BuildConfiguration: Release
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_VERSION: '3.1.x'

stages:
- stage: build
  jobs:  
  - job: "build"
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: $(DOTNET_VERSION)
    
    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

  - job: "test"
    strategy:
      matrix:
        gitlab-13:
          imageName: 'gitlab/gitlab-ee:13.2.4-ee.0' # Keep in sync with the version in GitLabDockerContainer.cs
        gitlab-12:
          imageName: 'gitlab/gitlab-ee:12.10.11-ee.0'
    pool:
      vmImage: ubuntu-latest
    services:
      gitlab:
        image: $(imageName)
        ports:
        - 48624:80
    steps:
    - script: curl http://localhost:48624/
      displayName: "Test GitLab is accessible"

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: $(DOTNET_VERSION)
    
    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Run tests
      inputs:
        command: test
        arguments: '--configuration $(BuildConfiguration)'
        projects: '**/*Tests.csproj'
        nobuild: true

  - job: "create_nuget"
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: $(DOTNET_VERSION)

    - task: DotNetCoreCLI@2
      displayName: dotnet pack
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        configuration: '$(BuildConfiguration)'
        packDirectory: '$(Build.ArtifactStagingDirectory)'
        versioningScheme: 'off'

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: NuGetPackages

- stage: deploy
  jobs:
  - job: "deploy_nuget"
    pool:
      vmImage: 'windows-2019'
    steps:
    - checkout: none

    - download: current
      artifact: NuGetPackages
      
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: $(DOTNET_VERSION)

    - powershell: |
        Write-Host "Searching nupkg in folder: $(Pipeline.Workspace)"
        $files = Get-ChildItem $(Pipeline.Workspace)/NuGetPackages/* -Include *.nupkg
        foreach($file in $files) {
            Write-Host "Pushing NuGet package: $($file.FullName)"
            if ($env:Build_SourceBranch -eq 'refs/heads/master')
            {
              # Push both nupkg and snupkg
              & dotnet nuget push "$($file.FullName)" --api-key "$(NuGetApiKey)" --source https://api.nuget.org/v3/index.json --force-english-output --skip-duplicate
            }
            else
            {
              Write-Host "Not on the default branch => Do not push"
            }
        }
      ignoreLASTEXITCODE: true
      displayName: Publish NuGet packages
      continueOnError: true
