// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.GitLabObjectJsonConverterFactory))]
    public partial class Group : Meziantou.GitLab.Core.GitLabObject, System.IEquatable<Meziantou.GitLab.Group>
    {
        internal Group(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("auto_devops_enabled")]
        public bool AutoDevopsEnabled
        {
            get
            {
                return this.GetRequiredNonNullValue<bool>("auto_devops_enabled");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("created_at")]
        public System.DateTimeOffset CreatedAt
        {
            get
            {
                return this.GetRequiredNonNullValue<System.DateTimeOffset>("created_at");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("description")]
        public string? Description
        {
            get
            {
                return this.GetValueOrDefault<string?>("description", default(string?));
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("id")]
        public long Id
        {
            get
            {
                return this.GetRequiredNonNullValue<long>("id");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("name")]
        public string Name
        {
            get
            {
                return this.GetRequiredNonNullValue<string>("name");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("name_with_namespace")]
        public string NameWithNamespace
        {
            get
            {
                return this.GetRequiredNonNullValue<string>("name_with_namespace");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("path")]
        public string Path
        {
            get
            {
                return this.GetRequiredNonNullValue<string>("path");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("path_with_namespace")]
        public Meziantou.GitLab.PathWithNamespace PathWithNamespace
        {
            get
            {
                return this.GetRequiredNonNullValue<Meziantou.GitLab.PathWithNamespace>("path_with_namespace");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("project_creation_level")]
        public ProjectCreationLevel ProjectCreationLevel
        {
            get
            {
                return this.GetRequiredNonNullValue<ProjectCreationLevel>("project_creation_level");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("visibility")]
        public Visibility Visibility
        {
            get
            {
                return this.GetRequiredNonNullValue<Visibility>("visibility");
            }
        }

        public override bool Equals(object? obj)
        {
            return this.Equals((obj as Meziantou.GitLab.Group));
        }

        public virtual bool Equals(Meziantou.GitLab.Group? other)
        {
            return ((!object.ReferenceEquals(other, null)) && (this.Id == other.Id));
        }

        public override int GetHashCode()
        {
            return System.HashCode.Combine(this.Id);
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Design", "MA0075:Do not use implicit culture-sensitive ToString", Justification = "Valid in ToString")]
        public override string ToString()
        {
            return (((((("Group { " + "Id = ") + this.Id) + ", ") + "PathWithNamespace = ") + this.PathWithNamespace) + " }");
        }

        public static bool operator !=(Meziantou.GitLab.Group? a, Meziantou.GitLab.Group? b)
        {
            return (!(a == b));
        }

        public static bool operator ==(Meziantou.GitLab.Group? a, Meziantou.GitLab.Group? b)
        {
            return System.Collections.Generic.EqualityComparer<Meziantou.GitLab.Group>.Default.Equals(a, b);
        }
    }
}
