// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.GitLabObjectJsonConverterFactory))]
    public partial class ProjectPermissions : Meziantou.GitLab.Core.GitLabObject
    {
        internal ProjectPermissions(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("group_access")]
        public GroupAccess GroupAccess
        {
            get
            {
                return this.GetRequiredNonNullValue<GroupAccess>("group_access");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("project_access")]
        public ProjectAccess ProjectAccess
        {
            get
            {
                return this.GetRequiredNonNullValue<ProjectAccess>("project_access");
            }
        }
    }
}
