// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.ProjectPermissionsJsonConverter))]
    public partial class ProjectPermissions : Meziantou.GitLab.Core.GitLabObject
    {
        internal ProjectPermissions(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }

        [Meziantou.GitLab.MappedPropertyAttribute("group_access")]
        public GroupAccess GroupAccess
        {
            get
            {
                return this.GetRequiredNonNullValue<GroupAccess>("group_access");
            }
        }

        [Meziantou.GitLab.MappedPropertyAttribute("project_access")]
        public ProjectAccess ProjectAccess
        {
            get
            {
                return this.GetRequiredNonNullValue<ProjectAccess>("project_access");
            }
        }
    }
}

namespace Meziantou.GitLab.Serialization
{
    internal sealed partial class ProjectPermissionsJsonConverter : Meziantou.GitLab.Serialization.GitLabObjectBaseJsonConverter<Meziantou.GitLab.ProjectPermissions>
    {
        protected override Meziantou.GitLab.ProjectPermissions CreateInstance(System.Text.Json.JsonElement jsonElement)
        {
            return new Meziantou.GitLab.ProjectPermissions(jsonElement);
        }
    }
}
