// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.ProjectAccessJsonConverter))]
    public partial class ProjectAccess : MemberAccess
    {
        internal ProjectAccess(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }
    }
}

namespace Meziantou.GitLab.Serialization
{
    internal sealed partial class ProjectAccessJsonConverter : Meziantou.GitLab.Serialization.GitLabObjectBaseJsonConverter<Meziantou.GitLab.ProjectAccess>
    {
        protected override Meziantou.GitLab.ProjectAccess CreateInstance(System.Text.Json.JsonElement jsonElement)
        {
            return new Meziantou.GitLab.ProjectAccess(jsonElement);
        }
    }
}
