// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    public enum ProjectCreationLevel
    {
        NoOne,
        Developer,
        Maintainer
    }
}

namespace Meziantou.GitLab.Internals
{
    internal partial struct UrlBuilder
    {
        public void AppendParameter(Meziantou.GitLab.ProjectCreationLevel value)
        {
            this.AppendParameter(((int)value));
        }

        public void AppendRawParameter(Meziantou.GitLab.ProjectCreationLevel value)
        {
            this.AppendParameter(((int)value));
        }
    }
}
