// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.ServerVersionJsonConverter))]
    public partial class ServerVersion : Meziantou.GitLab.Core.GitLabObject, System.IEquatable<Meziantou.GitLab.ServerVersion>
    {
        internal ServerVersion(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("revision")]
        public string Revision
        {
            get
            {
                return this.GetRequiredNonNullValue<string>("revision");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("version")]
        public string Version
        {
            get
            {
                return this.GetRequiredNonNullValue<string>("version");
            }
        }

        public override bool Equals(object? obj)
        {
            return this.Equals((obj as Meziantou.GitLab.ServerVersion));
        }

        public virtual bool Equals(Meziantou.GitLab.ServerVersion? obj)
        {
            return (((!object.ReferenceEquals(obj, null)) && (this.Version == obj.Version)) && (this.Revision == obj.Revision));
        }

        public override int GetHashCode()
        {
            return System.HashCode.Combine(this.Version, this.Revision);
        }

        public static bool operator !=(Meziantou.GitLab.ServerVersion? a, Meziantou.GitLab.ServerVersion? b)
        {
            return (!(a == b));
        }

        public static bool operator ==(Meziantou.GitLab.ServerVersion? a, Meziantou.GitLab.ServerVersion? b)
        {
            return System.Collections.Generic.EqualityComparer<Meziantou.GitLab.ServerVersion>.Default.Equals(a, b);
        }
    }
}

namespace Meziantou.GitLab.Serialization
{
    internal sealed partial class ServerVersionJsonConverter : Meziantou.GitLab.Serialization.GitLabObjectBaseJsonConverter<Meziantou.GitLab.ServerVersion>
    {
        protected override Meziantou.GitLab.ServerVersion CreateInstance(System.Text.Json.JsonElement jsonElement)
        {
            return new Meziantou.GitLab.ServerVersion(jsonElement);
        }
    }
}
