// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.GitLabObjectJsonConverterFactory))]
    public partial class SystemHook : Meziantou.GitLab.Core.GitLabObject, System.IEquatable<Meziantou.GitLab.SystemHook>
    {
        internal SystemHook(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("created_at")]
        public System.DateTimeOffset CreatedAt
        {
            get
            {
                return this.GetRequiredNonNullValue<System.DateTimeOffset>("created_at");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("enable_ssl_verification")]
        public bool EnableSslVerification
        {
            get
            {
                return this.GetRequiredNonNullValue<bool>("enable_ssl_verification");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("id")]
        public long Id
        {
            get
            {
                return this.GetRequiredNonNullValue<long>("id");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("merge_requests_events")]
        public bool MergeRequestsEvents
        {
            get
            {
                return this.GetRequiredNonNullValue<bool>("merge_requests_events");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("push_events")]
        public bool PushEvents
        {
            get
            {
                return this.GetRequiredNonNullValue<bool>("push_events");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("repository_update_events")]
        public bool RepositoryUpdateEvents
        {
            get
            {
                return this.GetRequiredNonNullValue<bool>("repository_update_events");
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("tag_push_events")]
        public bool TagPushEvents
        {
            get
            {
                return this.GetRequiredNonNullValue<bool>("tag_push_events");
            }
        }

        /// <remarks>The value is an absolute URI</remarks>
        [Meziantou.GitLab.Internals.MappedPropertyAttribute("url")]
        public System.Uri Url
        {
            get
            {
                return this.GetRequiredNonNullValue<System.Uri>("url");
            }
        }

        public override bool Equals(object? obj)
        {
            return this.Equals((obj as Meziantou.GitLab.SystemHook));
        }

        public virtual bool Equals(Meziantou.GitLab.SystemHook? other)
        {
            return ((!object.ReferenceEquals(other, null)) && (this.Id == other.Id));
        }

        public override int GetHashCode()
        {
            return System.HashCode.Combine(this.Id);
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Design", "MA0075:Do not use implicit culture-sensitive ToString", Justification = "Valid in ToString")]
        public override string ToString()
        {
            return (((((("SystemHook { " + "Id = ") + this.Id) + ", ") + "Url = ") + this.Url) + " }");
        }

        public static bool operator !=(Meziantou.GitLab.SystemHook? a, Meziantou.GitLab.SystemHook? b)
        {
            return (!(a == b));
        }

        public static bool operator ==(Meziantou.GitLab.SystemHook? a, Meziantou.GitLab.SystemHook? b)
        {
            return System.Collections.Generic.EqualityComparer<Meziantou.GitLab.SystemHook>.Default.Equals(a, b);
        }
    }
}
