// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.GitLabObjectReferenceJsonConverterFactory))]
    public readonly partial struct SystemHookIdRef : Meziantou.GitLab.Internals.IGitLabObjectReference<long>, System.IEquatable<Meziantou.GitLab.SystemHookIdRef>
    {
        private readonly long _value;

        private SystemHookIdRef(long systemHookId)
        {
            this._value = systemHookId;
        }

        private SystemHookIdRef(SystemHook systemHook)
        {
            if ((systemHook == null))
            {
                throw new System.ArgumentNullException(nameof(systemHook));
            }

            this._value = systemHook.Id;
        }

        public long Value
        {
            get
            {
                return this._value;
            }
        }

        public override bool Equals(object? obj)
        {
            if ((obj is Meziantou.GitLab.SystemHookIdRef))
            {
                return this.Equals(((Meziantou.GitLab.SystemHookIdRef)obj));
            }
            else
            {
                return false;
            }
        }

        public bool Equals(Meziantou.GitLab.SystemHookIdRef other)
        {
            return object.Equals(this.Value, other.Value);
        }

        public static Meziantou.GitLab.SystemHookIdRef FromSystemHook(SystemHook systemHook)
        {
            if ((systemHook == null))
            {
                throw new System.ArgumentNullException(nameof(systemHook));
            }

            return new Meziantou.GitLab.SystemHookIdRef(systemHook);
        }

        public static Meziantou.GitLab.SystemHookIdRef FromSystemHookId(long systemHookId)
        {
            return new Meziantou.GitLab.SystemHookIdRef(systemHookId);
        }

        public override int GetHashCode()
        {
            return System.HashCode.Combine(this.Value);
        }

        public override string ToString()
        {
            return this.Value.ToString(System.Globalization.CultureInfo.InvariantCulture);
        }

        public static implicit operator Meziantou.GitLab.SystemHookIdRef(long systemHookId)
        {
            return Meziantou.GitLab.SystemHookIdRef.FromSystemHookId(systemHookId);
        }

        public static implicit operator Meziantou.GitLab.SystemHookIdRef?(long? systemHookId)
        {
            if (systemHookId.HasValue)
            {
                return Meziantou.GitLab.SystemHookIdRef.FromSystemHookId(systemHookId.Value);
            }
            else
            {
                return null;
            }
        }

        public static implicit operator Meziantou.GitLab.SystemHookIdRef(SystemHook systemHook)
        {
            return Meziantou.GitLab.SystemHookIdRef.FromSystemHook(systemHook);
        }

        public static implicit operator Meziantou.GitLab.SystemHookIdRef?(SystemHook? systemHook)
        {
            if (object.ReferenceEquals(systemHook, null))
            {
                return null;
            }
            else
            {
                return Meziantou.GitLab.SystemHookIdRef.FromSystemHook(systemHook);
            }
        }

        public static bool operator !=(Meziantou.GitLab.SystemHookIdRef a, Meziantou.GitLab.SystemHookIdRef b)
        {
            return (!(a == b));
        }

        public static bool operator ==(Meziantou.GitLab.SystemHookIdRef a, Meziantou.GitLab.SystemHookIdRef b)
        {
            return System.Collections.Generic.EqualityComparer<Meziantou.GitLab.SystemHookIdRef>.Default.Equals(a, b);
        }
    }
}
