// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.GitLabObjectJsonConverterFactory))]
    public partial class UserStatus : Meziantou.GitLab.Core.GitLabObject
    {
        internal UserStatus(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("emoji")]
        public string? Emoji
        {
            get
            {
                return this.GetValueOrDefault<string?>("emoji", default(string?));
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("message")]
        public string? Message
        {
            get
            {
                return this.GetValueOrDefault<string?>("message", default(string?));
            }
        }

        [Meziantou.GitLab.Internals.MappedPropertyAttribute("message_html")]
        public string MessageHtml
        {
            get
            {
                return this.GetRequiredNonNullValue<string>("message_html");
            }
        }
    }
}
