// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.UsersOrderByJsonConverter))]
    public enum UsersOrderBy
    {
        [System.Runtime.Serialization.EnumMemberAttribute(Value = "id")]
        Id,
        [System.Runtime.Serialization.EnumMemberAttribute(Value = "name")]
        Name,
        [System.Runtime.Serialization.EnumMemberAttribute(Value = "username")]
        Username,
        [System.Runtime.Serialization.EnumMemberAttribute(Value = "created_at")]
        CreatedAt,
        [System.Runtime.Serialization.EnumMemberAttribute(Value = "updated_at")]
        UpdatedAt
    }
}

namespace Meziantou.GitLab.Serialization
{
    internal partial class EnumMember
    {
        private static readonly Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.UsersOrderBy>[] s_usersOrderByMembers = Meziantou.GitLab.Serialization.EnumMember.CreateUsersOrderByMembers();

        public static string ToString(Meziantou.GitLab.UsersOrderBy value)
        {
            if ((value == Meziantou.GitLab.UsersOrderBy.Id))
            {
                return "id";
            }

            if ((value == Meziantou.GitLab.UsersOrderBy.Name))
            {
                return "name";
            }

            if ((value == Meziantou.GitLab.UsersOrderBy.Username))
            {
                return "username";
            }

            if ((value == Meziantou.GitLab.UsersOrderBy.CreatedAt))
            {
                return "created_at";
            }

            if ((value == Meziantou.GitLab.UsersOrderBy.UpdatedAt))
            {
                return "updated_at";
            }

            throw new System.ArgumentOutOfRangeException(nameof(value), string.Concat("Value '", value.ToString(), "' is not valid"));
        }

        public static Meziantou.GitLab.UsersOrderBy UsersOrderByFromString(string value)
        {
            return Meziantou.GitLab.Serialization.EnumMember.FromString(value, Meziantou.GitLab.Serialization.EnumMember.s_usersOrderByMembers);
        }

        private static Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.UsersOrderBy>[] CreateUsersOrderByMembers()
        {
            Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.UsersOrderBy>[] result = new Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.UsersOrderBy>[5];
            result[0] = new Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.UsersOrderBy>(Meziantou.GitLab.UsersOrderBy.Id, "id");
            result[1] = new Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.UsersOrderBy>(Meziantou.GitLab.UsersOrderBy.Name, "name");
            result[2] = new Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.UsersOrderBy>(Meziantou.GitLab.UsersOrderBy.Username, "username");
            result[3] = new Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.UsersOrderBy>(Meziantou.GitLab.UsersOrderBy.CreatedAt, "created_at");
            result[4] = new Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.UsersOrderBy>(Meziantou.GitLab.UsersOrderBy.UpdatedAt, "updated_at");
            return result;
        }
    }

    internal sealed partial class UsersOrderByJsonConverter : Meziantou.GitLab.Serialization.EnumBaseJsonConverter<Meziantou.GitLab.UsersOrderBy>
    {
        protected override Meziantou.GitLab.UsersOrderBy FromString(string value)
        {
            return Meziantou.GitLab.Serialization.EnumMember.UsersOrderByFromString(value);
        }

        protected override string ToString(Meziantou.GitLab.UsersOrderBy value)
        {
            return Meziantou.GitLab.Serialization.EnumMember.ToString(value);
        }
    }
}

namespace Meziantou.GitLab.Internals
{
    internal partial struct UrlBuilder
    {
        public void AppendParameter(Meziantou.GitLab.UsersOrderBy value)
        {
            this.Append(Meziantou.GitLab.Serialization.EnumMember.ToString(value));
        }

        public void AppendRawParameter(Meziantou.GitLab.UsersOrderBy value)
        {
            this.Append(Meziantou.GitLab.Serialization.EnumMember.ToString(value));
        }
    }
}
