// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.GitLabObjectJsonConverterFactory))]
    public partial class UserAvatar : Meziantou.GitLab.Core.GitLabObject
    {
        internal UserAvatar(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }

        /// <remarks>The value is an absolute URI</remarks>
        [Meziantou.GitLab.Internals.MappedPropertyAttribute("avatar_url")]
        public System.Uri AvatarUrl
        {
            get
            {
                return this.GetRequiredNonNullValue<System.Uri>("avatar_url");
            }
        }
    }
}
