// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.VisibilityJsonConverter))]
    public enum Visibility
    {
        [System.Runtime.Serialization.EnumMemberAttribute(Value = "private")]
        Private,
        [System.Runtime.Serialization.EnumMemberAttribute(Value = "internal")]
        Internal,
        [System.Runtime.Serialization.EnumMemberAttribute(Value = "public")]
        Public
    }
}

namespace Meziantou.GitLab.Serialization
{
    internal partial class EnumMember
    {
        private static readonly Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.Visibility>[] s_visibilityMembers = Meziantou.GitLab.Serialization.EnumMember.CreateVisibilityMembers();

        public static string ToString(Meziantou.GitLab.Visibility value)
        {
            if ((value == Meziantou.GitLab.Visibility.Private))
            {
                return "private";
            }

            if ((value == Meziantou.GitLab.Visibility.Internal))
            {
                return "internal";
            }

            if ((value == Meziantou.GitLab.Visibility.Public))
            {
                return "public";
            }

            throw new System.ArgumentOutOfRangeException(nameof(value), string.Concat("Value '", value.ToString(), "' is not valid"));
        }

        public static Meziantou.GitLab.Visibility VisibilityFromString(string value)
        {
            return Meziantou.GitLab.Serialization.EnumMember.FromString(value, Meziantou.GitLab.Serialization.EnumMember.s_visibilityMembers);
        }

        private static Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.Visibility>[] CreateVisibilityMembers()
        {
            Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.Visibility>[] result = new Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.Visibility>[3];
            result[0] = new Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.Visibility>(Meziantou.GitLab.Visibility.Private, "private");
            result[1] = new Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.Visibility>(Meziantou.GitLab.Visibility.Internal, "internal");
            result[2] = new Meziantou.GitLab.Serialization.EnumMember<Meziantou.GitLab.Visibility>(Meziantou.GitLab.Visibility.Public, "public");
            return result;
        }
    }

    internal sealed partial class VisibilityJsonConverter : Meziantou.GitLab.Serialization.EnumBaseJsonConverter<Meziantou.GitLab.Visibility>
    {
        protected override Meziantou.GitLab.Visibility FromString(string value)
        {
            return Meziantou.GitLab.Serialization.EnumMember.VisibilityFromString(value);
        }

        protected override string ToString(Meziantou.GitLab.Visibility value)
        {
            return Meziantou.GitLab.Serialization.EnumMember.ToString(value);
        }
    }
}

namespace Meziantou.GitLab.Internals
{
    internal partial struct UrlBuilder
    {
        public void AppendParameter(Meziantou.GitLab.Visibility value)
        {
            this.Append(Meziantou.GitLab.Serialization.EnumMember.ToString(value));
        }
    }
}
