// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.FileCreatedJsonConverter))]
    public partial class FileCreated : Meziantou.GitLab.Core.GitLabObject
    {
        internal FileCreated(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }

        [Meziantou.GitLab.MappedPropertyAttribute("branch")]
        public string Branch
        {
            get
            {
                return this.GetValueOrDefault<string>("branch", default(string));
            }
        }

        [Meziantou.GitLab.MappedPropertyAttribute("file_path")]
        public string FilePath
        {
            get
            {
                return this.GetValueOrDefault<string>("file_path", default(string));
            }
        }
    }
}

namespace Meziantou.GitLab.Serialization
{
    internal sealed partial class FileCreatedJsonConverter : Meziantou.GitLab.Serialization.GitLabObjectBaseJsonConverter<Meziantou.GitLab.FileCreated>
    {
        protected override Meziantou.GitLab.FileCreated CreateInstance(System.Text.Json.JsonElement jsonElement)
        {
            return new Meziantou.GitLab.FileCreated(jsonElement);
        }
    }
}
#nullable disable
