// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.MemberAccessJsonConverter))]
    public partial class MemberAccess : Meziantou.GitLab.Core.GitLabObject
    {
        internal MemberAccess(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }

        [Meziantou.GitLab.MappedPropertyAttribute("access_level")]
        public AccessLevel AccessLevel
        {
            get
            {
                return this.GetRequiredNonNullValue<AccessLevel>("access_level");
            }
        }

        [Meziantou.GitLab.MappedPropertyAttribute("notification_level")]
        public string NotificationLevel
        {
            get
            {
                return this.GetRequiredNonNullValue<string>("notification_level");
            }
        }
    }
}

namespace Meziantou.GitLab.Serialization
{
    internal sealed partial class MemberAccessJsonConverter : Meziantou.GitLab.Serialization.GitLabObjectBaseJsonConverter<Meziantou.GitLab.MemberAccess>
    {
        protected override Meziantou.GitLab.MemberAccess CreateInstance(System.Text.Json.JsonElement jsonElement)
        {
            return new Meziantou.GitLab.MemberAccess(jsonElement);
        }
    }
}
