// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.GitLabObjectObjectReferenceJsonConverter))]
    public readonly partial struct ProjectIdOrPathRef : Meziantou.GitLab.IGitLabObjectReference<object>, System.IEquatable<Meziantou.GitLab.ProjectIdOrPathRef>
    {
        private readonly object _value;

        private ProjectIdOrPathRef(ProjectIdentity project)
        {
            if ((project == null))
            {
                throw new System.ArgumentNullException(nameof(project));
            }

            this._value = project.Id;
        }

        private ProjectIdOrPathRef(Meziantou.GitLab.PathWithNamespace projectPathWithNamespace)
        {
            this._value = projectPathWithNamespace;
        }

        private ProjectIdOrPathRef(long projectId)
        {
            this._value = projectId;
        }

        public object Value
        {
            get
            {
                return this._value;
            }
        }

        public override bool Equals(object? obj)
        {
            if ((obj is Meziantou.GitLab.ProjectIdOrPathRef))
            {
                return this.Equals(((Meziantou.GitLab.ProjectIdOrPathRef)obj));
            }
            else
            {
                return false;
            }
        }

        public bool Equals(Meziantou.GitLab.ProjectIdOrPathRef obj)
        {
            return object.Equals(this.Value, obj.Value);
        }

        public static Meziantou.GitLab.ProjectIdOrPathRef FromProject(ProjectIdentity project)
        {
            if ((project == null))
            {
                throw new System.ArgumentNullException(nameof(project));
            }

            return new Meziantou.GitLab.ProjectIdOrPathRef(project);
        }

        public static Meziantou.GitLab.ProjectIdOrPathRef FromProjectId(long projectId)
        {
            return new Meziantou.GitLab.ProjectIdOrPathRef(projectId);
        }

        public static Meziantou.GitLab.ProjectIdOrPathRef FromProjectPathWithNamespace(Meziantou.GitLab.PathWithNamespace projectPathWithNamespace)
        {
            return new Meziantou.GitLab.ProjectIdOrPathRef(projectPathWithNamespace);
        }

        public override int GetHashCode()
        {
            return System.HashCode.Combine(this.Value);
        }

        public override string? ToString()
        {
            return this.Value.ToString();
        }

        public static implicit operator Meziantou.GitLab.ProjectIdOrPathRef(long projectId)
        {
            return Meziantou.GitLab.ProjectIdOrPathRef.FromProjectId(projectId);
        }

        public static implicit operator Meziantou.GitLab.ProjectIdOrPathRef(ProjectIdentity project)
        {
            return Meziantou.GitLab.ProjectIdOrPathRef.FromProject(project);
        }

        public static implicit operator Meziantou.GitLab.ProjectIdOrPathRef(Meziantou.GitLab.PathWithNamespace projectPathWithNamespace)
        {
            return Meziantou.GitLab.ProjectIdOrPathRef.FromProjectPathWithNamespace(projectPathWithNamespace);
        }

        public static bool operator !=(Meziantou.GitLab.ProjectIdOrPathRef a, Meziantou.GitLab.ProjectIdOrPathRef b)
        {
            return (!(a == b));
        }

        public static bool operator ==(Meziantou.GitLab.ProjectIdOrPathRef a, Meziantou.GitLab.ProjectIdOrPathRef b)
        {
            return System.Collections.Generic.EqualityComparer<Meziantou.GitLab.ProjectIdOrPathRef>.Default.Equals(a, b);
        }
    }
}
