// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    [System.Text.Json.Serialization.JsonConverterAttribute(typeof(Meziantou.GitLab.Serialization.UserActivityJsonConverter))]
    public partial class UserActivity : Meziantou.GitLab.Core.GitLabObject
    {
        internal UserActivity(System.Text.Json.JsonElement obj)
            : base(obj)
        {
        }

        [Meziantou.GitLab.SkipUtcDateValidationAttribute("Does not contain time nor timezone (e.g. 2018-01-01)")]
        [Meziantou.GitLab.MappedPropertyAttribute("last_activity_on")]
        public System.DateTime LastActivityOn
        {
            get
            {
                return this.GetRequiredNonNullValue<System.DateTime>("last_activity_on");
            }
        }

        [Meziantou.GitLab.MappedPropertyAttribute("username")]
        public string Username
        {
            get
            {
                return this.GetRequiredNonNullValue<string>("username");
            }
        }
    }
}

namespace Meziantou.GitLab.Serialization
{
    internal sealed partial class UserActivityJsonConverter : Meziantou.GitLab.Serialization.GitLabObjectBaseJsonConverter<Meziantou.GitLab.UserActivity>
    {
        protected override Meziantou.GitLab.UserActivity CreateInstance(System.Text.Json.JsonElement jsonElement)
        {
            return new Meziantou.GitLab.UserActivity(jsonElement);
        }
    }
}
#nullable disable
