// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    public partial interface IGitLabClient
    {
        Meziantou.GitLab.IGitLabJobsClient Jobs
        {
            get;
        }
    }

    public partial interface IGitLabJobsClient
    {
        /// <summary>
        ///   <para>URL: <c>GET /projects/:id/jobs/:job_id</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/jobs.html#get-a-single-job" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        System.Threading.Tasks.Task<Job?> GetJobAsync(Meziantou.GitLab.GetJobRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        ///   <para>URL: <c>GET /projects/:id/jobs</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/jobs.html#list-project-jobs" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        Meziantou.GitLab.PagedResponse<Job> GetJobs(Meziantou.GitLab.GetJobsRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions));
    }

    public partial class GitLabClient : Meziantou.GitLab.IGitLabJobsClient
    {
        /// <summary>
        ///   <para>URL: <c>GET /projects/:id/jobs/:job_id</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/jobs.html#get-a-single-job" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        System.Threading.Tasks.Task<Job?> Meziantou.GitLab.IGitLabJobsClient.GetJobAsync(Meziantou.GitLab.GetJobRequest request, Meziantou.GitLab.RequestOptions? requestOptions, System.Threading.CancellationToken cancellationToken)
        {
            return this.Jobs_GetJobAsync(request, requestOptions, cancellationToken);
        }

        /// <summary>
        ///   <para>URL: <c>GET /projects/:id/jobs</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/jobs.html#list-project-jobs" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        Meziantou.GitLab.PagedResponse<Job> Meziantou.GitLab.IGitLabJobsClient.GetJobs(Meziantou.GitLab.GetJobsRequest request, Meziantou.GitLab.RequestOptions? requestOptions)
        {
            return this.Jobs_GetJobs(request, requestOptions);
        }

        public Meziantou.GitLab.IGitLabJobsClient Jobs
        {
            get
            {
                return this;
            }
        }

        /// <summary>
        ///   <para>URL: <c>GET /projects/:id/jobs/:job_id</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/jobs.html#get-a-single-job" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        private async System.Threading.Tasks.Task<Job?> Jobs_GetJobAsync(Meziantou.GitLab.GetJobRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            string url = Meziantou.GitLab.GitLabClient.Jobs_GetJobAsync_BuildUrl(request);
            using (System.Net.Http.HttpRequestMessage requestMessage = new System.Net.Http.HttpRequestMessage())
            {
                requestMessage.Method = System.Net.Http.HttpMethod.Get;
                requestMessage.RequestUri = new System.Uri(url, System.UriKind.RelativeOrAbsolute);
                HttpResponse? response = null;
                try
                {
                    response = await this.SendAsync(requestMessage, requestOptions, cancellationToken).ConfigureAwait(false);
                    if ((response.StatusCode == System.Net.HttpStatusCode.NotFound))
                    {
                        return default;
                    }

                    await response.EnsureStatusCodeAsync(cancellationToken).ConfigureAwait(false);
                    Job? result = await response.ToObjectAsync<Job>(cancellationToken).ConfigureAwait(false);
                    return result;
                }
                finally
                {
                    if ((response != null))
                    {
                        response.Dispose();
                    }
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Reliability", "CA2000:Dispose objects before losing scope", Justification = "The rule doesn't understand ref struct")]
        private static string Jobs_GetJobAsync_BuildUrl(Meziantou.GitLab.GetJobRequest request)
        {
            string url;
            using (Meziantou.GitLab.Internals.UrlBuilder urlBuilder = new Meziantou.GitLab.Internals.UrlBuilder())
            {
                urlBuilder.Append("projects/");
                if (request.Id.HasValue)
                {
                    urlBuilder.AppendParameter(request.Id.GetValueOrDefault().ValueAsString);
                }

                urlBuilder.Append("/jobs/");
                if (request.JobId.HasValue)
                {
                    urlBuilder.AppendParameter(request.JobId.GetValueOrDefault().Value);
                }

                url = urlBuilder.ToString();
            }

            return url;
        }

        /// <summary>
        ///   <para>URL: <c>GET /projects/:id/jobs</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/jobs.html#list-project-jobs" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        private Meziantou.GitLab.PagedResponse<Job> Jobs_GetJobs(Meziantou.GitLab.GetJobsRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions))
        {
            string url = Meziantou.GitLab.GitLabClient.Jobs_GetJobs_BuildUrl(request);
            return new Meziantou.GitLab.PagedResponse<Job>(this, url, requestOptions);
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Reliability", "CA2000:Dispose objects before losing scope", Justification = "The rule doesn't understand ref struct")]
        private static string Jobs_GetJobs_BuildUrl(Meziantou.GitLab.GetJobsRequest request)
        {
            string url;
            using (Meziantou.GitLab.Internals.UrlBuilder urlBuilder = new Meziantou.GitLab.Internals.UrlBuilder())
            {
                urlBuilder.Append("projects/");
                if (request.Id.HasValue)
                {
                    urlBuilder.AppendParameter(request.Id.GetValueOrDefault().ValueAsString);
                }

                urlBuilder.Append("/jobs");
                url = urlBuilder.ToString();
            }

            return url;
        }
    }

    public static partial class GitLabClientExtensions
    {
        /// <summary>
        ///   <para>URL: <c>GET /projects/:id/jobs/:job_id</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/jobs.html#get-a-single-job" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        public static System.Threading.Tasks.Task<Job?> GetJobAsync(this Meziantou.GitLab.IGitLabJobsClient client, ProjectIdOrPathRef id, JobIdRef jobId, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Meziantou.GitLab.GetJobRequest request = new Meziantou.GitLab.GetJobRequest(id, jobId);
            return client.GetJobAsync(request, requestOptions, cancellationToken);
        }

        /// <summary>
        ///   <para>URL: <c>GET /projects/:id/jobs</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/jobs.html#list-project-jobs" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        public static Meziantou.GitLab.PagedResponse<Job> GetJobs(this Meziantou.GitLab.IGitLabJobsClient client, ProjectIdOrPathRef id, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions))
        {
            Meziantou.GitLab.GetJobsRequest request = new Meziantou.GitLab.GetJobsRequest(id);
            return client.GetJobs(request, requestOptions);
        }
    }

    public partial class GetJobRequest
    {
        private ProjectIdOrPathRef? _id;

        private JobIdRef? _jobId;

        /// <param name="id">ID or URL-encoded path of the project owned by the authenticated user.</param>
        /// <param name="jobId">ID of a job.</param>
        public GetJobRequest(ProjectIdOrPathRef? id, JobIdRef? jobId)
        {
            this._id = id;
            this._jobId = jobId;
        }

        public GetJobRequest()
        {
        }

        /// <summary>
        ///   <para>ID or URL-encoded path of the project owned by the authenticated user.</para>
        /// </summary>
        [System.Text.Json.Serialization.JsonIgnoreAttribute]
        public ProjectIdOrPathRef? Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }

        /// <summary>
        ///   <para>ID of a job.</para>
        /// </summary>
        [System.Text.Json.Serialization.JsonIgnoreAttribute]
        public JobIdRef? JobId
        {
            get
            {
                return this._jobId;
            }
            set
            {
                this._jobId = value;
            }
        }
    }

    public partial class GetJobsRequest
    {
        private ProjectIdOrPathRef? _id;

        /// <param name="id">ID or URL-encoded path of the project owned by the authenticated user.</param>
        public GetJobsRequest(ProjectIdOrPathRef? id)
        {
            this._id = id;
        }

        public GetJobsRequest()
        {
        }

        /// <summary>
        ///   <para>ID or URL-encoded path of the project owned by the authenticated user.</para>
        /// </summary>
        [System.Text.Json.Serialization.JsonIgnoreAttribute]
        public ProjectIdOrPathRef? Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
    }
}
