// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace Meziantou.GitLab
{
    public partial interface IGitLabClient
    {
        Meziantou.GitLab.IGitLabTemplatesClient Templates
        {
            get;
        }
    }

    public partial interface IGitLabTemplatesClient
    {
        /// <summary>
        ///   <para>URL: <c>GET /templates/dockerfiles/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/dockerfiles.html#single-dockerfile-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        System.Threading.Tasks.Task<Template?> GetDockerfileByKeyAsync(Meziantou.GitLab.GetDockerfileByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        ///   <para>URL: <c>GET /templates/dockerfiles</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/dockerfiles.html#list-dockerfile-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        Meziantou.GitLab.PagedResponse<TemplateBasic> GetDockerfiles(Meziantou.GitLab.GetDockerfilesTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions));

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitignores/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitignores.html#get-a-single-gitignore-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        System.Threading.Tasks.Task<Template?> GetGitIgnoreByKeyAsync(Meziantou.GitLab.GetGitIgnoreByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitignores</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitignores.html#get-all-gitignore-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        Meziantou.GitLab.PagedResponse<TemplateBasic> GetGitIgnores(Meziantou.GitLab.GetGitIgnoresTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions));

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitlab_ci_ymls/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html#single-gitlab-ci-yaml-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        System.Threading.Tasks.Task<Template?> GetGitLabCiYmlByKeyAsync(Meziantou.GitLab.GetGitLabCiYmlByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitlab_ci_ymls</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html#list-gitlab-ci-yaml-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        Meziantou.GitLab.PagedResponse<TemplateBasic> GetGitLabCiYmls(Meziantou.GitLab.GetGitLabCiYmlsTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions));

        /// <summary>
        ///   <para>URL: <c>GET /templates/licenses/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/licenses.html#single-license-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        System.Threading.Tasks.Task<Template?> GetLicenseByKeyAsync(Meziantou.GitLab.GetLicenseByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        ///   <para>URL: <c>GET /templates/licenses</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/licenses.html#list-license-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        Meziantou.GitLab.PagedResponse<TemplateBasic> GetLicenses(Meziantou.GitLab.GetLicensesTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions));
    }

    public partial class GitLabClient : Meziantou.GitLab.IGitLabTemplatesClient
    {
        /// <summary>
        ///   <para>URL: <c>GET /templates/dockerfiles/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/dockerfiles.html#single-dockerfile-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        System.Threading.Tasks.Task<Template?> Meziantou.GitLab.IGitLabTemplatesClient.GetDockerfileByKeyAsync(Meziantou.GitLab.GetDockerfileByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions, System.Threading.CancellationToken cancellationToken)
        {
            return this.Templates_GetDockerfileByKeyAsync(request, requestOptions, cancellationToken);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/dockerfiles</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/dockerfiles.html#list-dockerfile-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        Meziantou.GitLab.PagedResponse<TemplateBasic> Meziantou.GitLab.IGitLabTemplatesClient.GetDockerfiles(Meziantou.GitLab.GetDockerfilesTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions)
        {
            return this.Templates_GetDockerfiles(request, requestOptions);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitignores/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitignores.html#get-a-single-gitignore-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        System.Threading.Tasks.Task<Template?> Meziantou.GitLab.IGitLabTemplatesClient.GetGitIgnoreByKeyAsync(Meziantou.GitLab.GetGitIgnoreByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions, System.Threading.CancellationToken cancellationToken)
        {
            return this.Templates_GetGitIgnoreByKeyAsync(request, requestOptions, cancellationToken);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitignores</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitignores.html#get-all-gitignore-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        Meziantou.GitLab.PagedResponse<TemplateBasic> Meziantou.GitLab.IGitLabTemplatesClient.GetGitIgnores(Meziantou.GitLab.GetGitIgnoresTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions)
        {
            return this.Templates_GetGitIgnores(request, requestOptions);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitlab_ci_ymls/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html#single-gitlab-ci-yaml-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        System.Threading.Tasks.Task<Template?> Meziantou.GitLab.IGitLabTemplatesClient.GetGitLabCiYmlByKeyAsync(Meziantou.GitLab.GetGitLabCiYmlByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions, System.Threading.CancellationToken cancellationToken)
        {
            return this.Templates_GetGitLabCiYmlByKeyAsync(request, requestOptions, cancellationToken);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitlab_ci_ymls</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html#list-gitlab-ci-yaml-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        Meziantou.GitLab.PagedResponse<TemplateBasic> Meziantou.GitLab.IGitLabTemplatesClient.GetGitLabCiYmls(Meziantou.GitLab.GetGitLabCiYmlsTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions)
        {
            return this.Templates_GetGitLabCiYmls(request, requestOptions);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/licenses/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/licenses.html#single-license-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        System.Threading.Tasks.Task<Template?> Meziantou.GitLab.IGitLabTemplatesClient.GetLicenseByKeyAsync(Meziantou.GitLab.GetLicenseByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions, System.Threading.CancellationToken cancellationToken)
        {
            return this.Templates_GetLicenseByKeyAsync(request, requestOptions, cancellationToken);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/licenses</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/licenses.html#list-license-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        Meziantou.GitLab.PagedResponse<TemplateBasic> Meziantou.GitLab.IGitLabTemplatesClient.GetLicenses(Meziantou.GitLab.GetLicensesTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions)
        {
            return this.Templates_GetLicenses(request, requestOptions);
        }

        public Meziantou.GitLab.IGitLabTemplatesClient Templates
        {
            get
            {
                return this;
            }
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/dockerfiles/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/dockerfiles.html#single-dockerfile-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        private async System.Threading.Tasks.Task<Template?> Templates_GetDockerfileByKeyAsync(Meziantou.GitLab.GetDockerfileByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            string url = Meziantou.GitLab.GitLabClient.Templates_GetDockerfileByKeyAsync_BuildUrl(request);
            using (System.Net.Http.HttpRequestMessage requestMessage = new System.Net.Http.HttpRequestMessage())
            {
                requestMessage.Method = System.Net.Http.HttpMethod.Get;
                requestMessage.RequestUri = new System.Uri(url, System.UriKind.RelativeOrAbsolute);
                HttpResponse? response = null;
                try
                {
                    response = await this.SendAsync(requestMessage, requestOptions, cancellationToken).ConfigureAwait(false);
                    if ((response.StatusCode == System.Net.HttpStatusCode.NotFound))
                    {
                        return default;
                    }

                    await response.EnsureStatusCodeAsync(cancellationToken).ConfigureAwait(false);
                    Template? result = await response.ToObjectAsync<Template>(cancellationToken).ConfigureAwait(false);
                    if ((result == null))
                    {
                        throw new Meziantou.GitLab.GitLabException(response.RequestMethod, response.RequestUri, response.StatusCode, "The response cannot be converted to 'Template' because the body is null or empty");
                    }

                    return result;
                }
                finally
                {
                    if ((response != null))
                    {
                        response.Dispose();
                    }
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Reliability", "CA2000:Dispose objects before losing scope", Justification = "The rule doesn't understand ref struct")]
        private static string Templates_GetDockerfileByKeyAsync_BuildUrl(Meziantou.GitLab.GetDockerfileByKeyTemplateRequest request)
        {
            string url;
            using (Meziantou.GitLab.Internals.UrlBuilder urlBuilder = new Meziantou.GitLab.Internals.UrlBuilder())
            {
                urlBuilder.Append("templates/dockerfiles/");
                if ((!object.ReferenceEquals(request.Key, null)))
                {
                    urlBuilder.AppendParameter(request.Key);
                }

                url = urlBuilder.ToString();
            }

            return url;
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/dockerfiles</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/dockerfiles.html#list-dockerfile-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        private Meziantou.GitLab.PagedResponse<TemplateBasic> Templates_GetDockerfiles(Meziantou.GitLab.GetDockerfilesTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions))
        {
            string url = Meziantou.GitLab.GitLabClient.Templates_GetDockerfiles_BuildUrl();
            return new Meziantou.GitLab.PagedResponse<TemplateBasic>(this, url, requestOptions);
        }

        private static string Templates_GetDockerfiles_BuildUrl()
        {
            string url;
            url = "templates/dockerfiles";
            return url;
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitignores/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitignores.html#get-a-single-gitignore-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        private async System.Threading.Tasks.Task<Template?> Templates_GetGitIgnoreByKeyAsync(Meziantou.GitLab.GetGitIgnoreByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            string url = Meziantou.GitLab.GitLabClient.Templates_GetGitIgnoreByKeyAsync_BuildUrl(request);
            using (System.Net.Http.HttpRequestMessage requestMessage = new System.Net.Http.HttpRequestMessage())
            {
                requestMessage.Method = System.Net.Http.HttpMethod.Get;
                requestMessage.RequestUri = new System.Uri(url, System.UriKind.RelativeOrAbsolute);
                HttpResponse? response = null;
                try
                {
                    response = await this.SendAsync(requestMessage, requestOptions, cancellationToken).ConfigureAwait(false);
                    if ((response.StatusCode == System.Net.HttpStatusCode.NotFound))
                    {
                        return default;
                    }

                    await response.EnsureStatusCodeAsync(cancellationToken).ConfigureAwait(false);
                    Template? result = await response.ToObjectAsync<Template>(cancellationToken).ConfigureAwait(false);
                    if ((result == null))
                    {
                        throw new Meziantou.GitLab.GitLabException(response.RequestMethod, response.RequestUri, response.StatusCode, "The response cannot be converted to 'Template' because the body is null or empty");
                    }

                    return result;
                }
                finally
                {
                    if ((response != null))
                    {
                        response.Dispose();
                    }
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Reliability", "CA2000:Dispose objects before losing scope", Justification = "The rule doesn't understand ref struct")]
        private static string Templates_GetGitIgnoreByKeyAsync_BuildUrl(Meziantou.GitLab.GetGitIgnoreByKeyTemplateRequest request)
        {
            string url;
            using (Meziantou.GitLab.Internals.UrlBuilder urlBuilder = new Meziantou.GitLab.Internals.UrlBuilder())
            {
                urlBuilder.Append("templates/gitignores/");
                if ((!object.ReferenceEquals(request.Key, null)))
                {
                    urlBuilder.AppendParameter(request.Key);
                }

                url = urlBuilder.ToString();
            }

            return url;
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitignores</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitignores.html#get-all-gitignore-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        private Meziantou.GitLab.PagedResponse<TemplateBasic> Templates_GetGitIgnores(Meziantou.GitLab.GetGitIgnoresTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions))
        {
            string url = Meziantou.GitLab.GitLabClient.Templates_GetGitIgnores_BuildUrl();
            return new Meziantou.GitLab.PagedResponse<TemplateBasic>(this, url, requestOptions);
        }

        private static string Templates_GetGitIgnores_BuildUrl()
        {
            string url;
            url = "templates/gitignores";
            return url;
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitlab_ci_ymls/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html#single-gitlab-ci-yaml-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        private async System.Threading.Tasks.Task<Template?> Templates_GetGitLabCiYmlByKeyAsync(Meziantou.GitLab.GetGitLabCiYmlByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            string url = Meziantou.GitLab.GitLabClient.Templates_GetGitLabCiYmlByKeyAsync_BuildUrl(request);
            using (System.Net.Http.HttpRequestMessage requestMessage = new System.Net.Http.HttpRequestMessage())
            {
                requestMessage.Method = System.Net.Http.HttpMethod.Get;
                requestMessage.RequestUri = new System.Uri(url, System.UriKind.RelativeOrAbsolute);
                HttpResponse? response = null;
                try
                {
                    response = await this.SendAsync(requestMessage, requestOptions, cancellationToken).ConfigureAwait(false);
                    if ((response.StatusCode == System.Net.HttpStatusCode.NotFound))
                    {
                        return default;
                    }

                    await response.EnsureStatusCodeAsync(cancellationToken).ConfigureAwait(false);
                    Template? result = await response.ToObjectAsync<Template>(cancellationToken).ConfigureAwait(false);
                    if ((result == null))
                    {
                        throw new Meziantou.GitLab.GitLabException(response.RequestMethod, response.RequestUri, response.StatusCode, "The response cannot be converted to 'Template' because the body is null or empty");
                    }

                    return result;
                }
                finally
                {
                    if ((response != null))
                    {
                        response.Dispose();
                    }
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Reliability", "CA2000:Dispose objects before losing scope", Justification = "The rule doesn't understand ref struct")]
        private static string Templates_GetGitLabCiYmlByKeyAsync_BuildUrl(Meziantou.GitLab.GetGitLabCiYmlByKeyTemplateRequest request)
        {
            string url;
            using (Meziantou.GitLab.Internals.UrlBuilder urlBuilder = new Meziantou.GitLab.Internals.UrlBuilder())
            {
                urlBuilder.Append("templates/gitlab_ci_ymls/");
                if ((!object.ReferenceEquals(request.Key, null)))
                {
                    urlBuilder.AppendParameter(request.Key);
                }

                url = urlBuilder.ToString();
            }

            return url;
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitlab_ci_ymls</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html#list-gitlab-ci-yaml-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        private Meziantou.GitLab.PagedResponse<TemplateBasic> Templates_GetGitLabCiYmls(Meziantou.GitLab.GetGitLabCiYmlsTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions))
        {
            string url = Meziantou.GitLab.GitLabClient.Templates_GetGitLabCiYmls_BuildUrl();
            return new Meziantou.GitLab.PagedResponse<TemplateBasic>(this, url, requestOptions);
        }

        private static string Templates_GetGitLabCiYmls_BuildUrl()
        {
            string url;
            url = "templates/gitlab_ci_ymls";
            return url;
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/licenses/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/licenses.html#single-license-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        private async System.Threading.Tasks.Task<Template?> Templates_GetLicenseByKeyAsync(Meziantou.GitLab.GetLicenseByKeyTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            string url = Meziantou.GitLab.GitLabClient.Templates_GetLicenseByKeyAsync_BuildUrl(request);
            using (System.Net.Http.HttpRequestMessage requestMessage = new System.Net.Http.HttpRequestMessage())
            {
                requestMessage.Method = System.Net.Http.HttpMethod.Get;
                requestMessage.RequestUri = new System.Uri(url, System.UriKind.RelativeOrAbsolute);
                HttpResponse? response = null;
                try
                {
                    response = await this.SendAsync(requestMessage, requestOptions, cancellationToken).ConfigureAwait(false);
                    if ((response.StatusCode == System.Net.HttpStatusCode.NotFound))
                    {
                        return default;
                    }

                    await response.EnsureStatusCodeAsync(cancellationToken).ConfigureAwait(false);
                    Template? result = await response.ToObjectAsync<Template>(cancellationToken).ConfigureAwait(false);
                    if ((result == null))
                    {
                        throw new Meziantou.GitLab.GitLabException(response.RequestMethod, response.RequestUri, response.StatusCode, "The response cannot be converted to 'Template' because the body is null or empty");
                    }

                    return result;
                }
                finally
                {
                    if ((response != null))
                    {
                        response.Dispose();
                    }
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Reliability", "CA2000:Dispose objects before losing scope", Justification = "The rule doesn't understand ref struct")]
        private static string Templates_GetLicenseByKeyAsync_BuildUrl(Meziantou.GitLab.GetLicenseByKeyTemplateRequest request)
        {
            string url;
            using (Meziantou.GitLab.Internals.UrlBuilder urlBuilder = new Meziantou.GitLab.Internals.UrlBuilder())
            {
                urlBuilder.Append("templates/licenses/");
                if ((!object.ReferenceEquals(request.Key, null)))
                {
                    urlBuilder.AppendParameter(request.Key);
                }

                char separator = '?';
                if ((!object.ReferenceEquals(request.Project, null)))
                {
                    urlBuilder.Append(separator);
                    separator = '&';
                    urlBuilder.Append("project=");
                    urlBuilder.AppendParameter(request.Project);
                }

                if ((!object.ReferenceEquals(request.Fullname, null)))
                {
                    urlBuilder.Append(separator);
                    separator = '&';
                    urlBuilder.Append("fullname=");
                    urlBuilder.AppendParameter(request.Fullname);
                }

                url = urlBuilder.ToString();
            }

            return url;
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/licenses</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/licenses.html#list-license-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        private Meziantou.GitLab.PagedResponse<TemplateBasic> Templates_GetLicenses(Meziantou.GitLab.GetLicensesTemplateRequest request, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions))
        {
            string url = Meziantou.GitLab.GitLabClient.Templates_GetLicenses_BuildUrl(request);
            return new Meziantou.GitLab.PagedResponse<TemplateBasic>(this, url, requestOptions);
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Reliability", "CA2000:Dispose objects before losing scope", Justification = "The rule doesn't understand ref struct")]
        private static string Templates_GetLicenses_BuildUrl(Meziantou.GitLab.GetLicensesTemplateRequest request)
        {
            string url;
            using (Meziantou.GitLab.Internals.UrlBuilder urlBuilder = new Meziantou.GitLab.Internals.UrlBuilder())
            {
                urlBuilder.Append("templates/licenses");
                char separator = '?';
                if (request.Popular.HasValue)
                {
                    urlBuilder.Append(separator);
                    separator = '&';
                    urlBuilder.Append("popular=");
                    urlBuilder.AppendParameter(request.Popular.GetValueOrDefault());
                }

                url = urlBuilder.ToString();
            }

            return url;
        }
    }

    public static partial class GitLabClientExtensions
    {
        /// <summary>
        ///   <para>URL: <c>GET /templates/dockerfiles/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/dockerfiles.html#single-dockerfile-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        public static System.Threading.Tasks.Task<Template?> GetDockerfileByKeyAsync(this Meziantou.GitLab.IGitLabTemplatesClient client, string key, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Meziantou.GitLab.GetDockerfileByKeyTemplateRequest request = new Meziantou.GitLab.GetDockerfileByKeyTemplateRequest(key);
            return client.GetDockerfileByKeyAsync(request, requestOptions, cancellationToken);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/dockerfiles</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/dockerfiles.html#list-dockerfile-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        public static Meziantou.GitLab.PagedResponse<TemplateBasic> GetDockerfiles(this Meziantou.GitLab.IGitLabTemplatesClient client, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions))
        {
            Meziantou.GitLab.GetDockerfilesTemplateRequest request = new Meziantou.GitLab.GetDockerfilesTemplateRequest();
            return client.GetDockerfiles(request, requestOptions);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitignores/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitignores.html#get-a-single-gitignore-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        public static System.Threading.Tasks.Task<Template?> GetGitIgnoreByKeyAsync(this Meziantou.GitLab.IGitLabTemplatesClient client, string key, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Meziantou.GitLab.GetGitIgnoreByKeyTemplateRequest request = new Meziantou.GitLab.GetGitIgnoreByKeyTemplateRequest(key);
            return client.GetGitIgnoreByKeyAsync(request, requestOptions, cancellationToken);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitignores</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitignores.html#get-all-gitignore-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        public static Meziantou.GitLab.PagedResponse<TemplateBasic> GetGitIgnores(this Meziantou.GitLab.IGitLabTemplatesClient client, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions))
        {
            Meziantou.GitLab.GetGitIgnoresTemplateRequest request = new Meziantou.GitLab.GetGitIgnoresTemplateRequest();
            return client.GetGitIgnores(request, requestOptions);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitlab_ci_ymls/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html#single-gitlab-ci-yaml-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        public static System.Threading.Tasks.Task<Template?> GetGitLabCiYmlByKeyAsync(this Meziantou.GitLab.IGitLabTemplatesClient client, string key, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Meziantou.GitLab.GetGitLabCiYmlByKeyTemplateRequest request = new Meziantou.GitLab.GetGitLabCiYmlByKeyTemplateRequest(key);
            return client.GetGitLabCiYmlByKeyAsync(request, requestOptions, cancellationToken);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/gitlab_ci_ymls</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/gitlab_ci_ymls.html#list-gitlab-ci-yaml-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        public static Meziantou.GitLab.PagedResponse<TemplateBasic> GetGitLabCiYmls(this Meziantou.GitLab.IGitLabTemplatesClient client, Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions))
        {
            Meziantou.GitLab.GetGitLabCiYmlsTemplateRequest request = new Meziantou.GitLab.GetGitLabCiYmlsTemplateRequest();
            return client.GetGitLabCiYmls(request, requestOptions);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/licenses/:key</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/licenses.html#single-license-template" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation</param>
        public static System.Threading.Tasks.Task<Template?> GetLicenseByKeyAsync(this Meziantou.GitLab.IGitLabTemplatesClient client, string key, string? project = default(string?), string? fullname = default(string?), Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Meziantou.GitLab.GetLicenseByKeyTemplateRequest request = new Meziantou.GitLab.GetLicenseByKeyTemplateRequest(key);
            request.Project = project;
            request.Fullname = fullname;
            return client.GetLicenseByKeyAsync(request, requestOptions, cancellationToken);
        }

        /// <summary>
        ///   <para>URL: <c>GET /templates/licenses</c></para>
        ///   <para>
        ///     <seealso href="https://docs.gitlab.com/ee/api/templates/licenses.html#list-license-templates" />
        ///   </para>
        /// </summary>
        /// <param name="requestOptions">Options of the request</param>
        public static Meziantou.GitLab.PagedResponse<TemplateBasic> GetLicenses(this Meziantou.GitLab.IGitLabTemplatesClient client, bool? popular = default(bool?), Meziantou.GitLab.RequestOptions? requestOptions = default(Meziantou.GitLab.RequestOptions))
        {
            Meziantou.GitLab.GetLicensesTemplateRequest request = new Meziantou.GitLab.GetLicensesTemplateRequest();
            request.Popular = popular;
            return client.GetLicenses(request, requestOptions);
        }
    }

    public partial class GetGitIgnoresTemplateRequest
    {
        public GetGitIgnoresTemplateRequest()
        {
        }
    }

    public partial class GetGitIgnoreByKeyTemplateRequest
    {
        private string? _key;

        /// <param name="key">The key of the .gitignore template</param>
        public GetGitIgnoreByKeyTemplateRequest(string? key)
        {
            this._key = key;
        }

        public GetGitIgnoreByKeyTemplateRequest()
        {
        }

        /// <summary>
        ///   <para>The key of the .gitignore template</para>
        /// </summary>
        public string? Key
        {
            get
            {
                return this._key;
            }
            set
            {
                this._key = value;
            }
        }
    }

    public partial class GetGitLabCiYmlsTemplateRequest
    {
        public GetGitLabCiYmlsTemplateRequest()
        {
        }
    }

    public partial class GetGitLabCiYmlByKeyTemplateRequest
    {
        private string? _key;

        /// <param name="key">The key of the GitLab CI/CD YAML template</param>
        public GetGitLabCiYmlByKeyTemplateRequest(string? key)
        {
            this._key = key;
        }

        public GetGitLabCiYmlByKeyTemplateRequest()
        {
        }

        /// <summary>
        ///   <para>The key of the GitLab CI/CD YAML template</para>
        /// </summary>
        public string? Key
        {
            get
            {
                return this._key;
            }
            set
            {
                this._key = value;
            }
        }
    }

    public partial class GetDockerfilesTemplateRequest
    {
        public GetDockerfilesTemplateRequest()
        {
        }
    }

    public partial class GetDockerfileByKeyTemplateRequest
    {
        private string? _key;

        /// <param name="key">The key of the Dockerfile template</param>
        public GetDockerfileByKeyTemplateRequest(string? key)
        {
            this._key = key;
        }

        public GetDockerfileByKeyTemplateRequest()
        {
        }

        /// <summary>
        ///   <para>The key of the Dockerfile template</para>
        /// </summary>
        public string? Key
        {
            get
            {
                return this._key;
            }
            set
            {
                this._key = value;
            }
        }
    }

    public partial class GetLicensesTemplateRequest
    {
        private bool? _popular;

        public GetLicensesTemplateRequest()
        {
        }

        /// <summary>
        ///   <para>If passed, returns only popular licenses</para>
        /// </summary>
        public bool? Popular
        {
            get
            {
                return this._popular;
            }
            set
            {
                this._popular = value;
            }
        }
    }

    public partial class GetLicenseByKeyTemplateRequest
    {
        private string? _fullname;

        private string? _key;

        private string? _project;

        /// <param name="key">The key of the license template</param>
        public GetLicenseByKeyTemplateRequest(string? key)
        {
            this._key = key;
        }

        public GetLicenseByKeyTemplateRequest()
        {
        }

        /// <summary>
        ///   <para>The full-name of the copyright holder</para>
        /// </summary>
        public string? Fullname
        {
            get
            {
                return this._fullname;
            }
            set
            {
                this._fullname = value;
            }
        }

        /// <summary>
        ///   <para>The key of the license template</para>
        /// </summary>
        public string? Key
        {
            get
            {
                return this._key;
            }
            set
            {
                this._key = value;
            }
        }

        /// <summary>
        ///   <para>The copyrighted project name</para>
        /// </summary>
        public string? Project
        {
            get
            {
                return this._project;
            }
            set
            {
                this._project = value;
            }
        }
    }
}
